{"name":"Log","hostname":"vultr.guest","pid":20319,"level":50,"err":{"id":"0f15aa60-60c6-11e9-8e06-29aeed8a9965","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:05:38.442Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20359,"level":50,"err":{"id":"11ea7540-60c6-11e9-8b48-6f7ee1c18a34","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:05:43.193Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20387,"level":50,"err":{"id":"15946a70-60c6-11e9-833c-ab2efdec3652","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:05:49.366Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20415,"level":50,"err":{"id":"18954e60-60c6-11e9-99da-b9d674a8ddc2","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:05:54.397Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20443,"level":50,"err":{"id":"209a8760-60c6-11e9-8273-4b97b60d0dac","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)\n    at runNextTicks (internal/process/task_queues.js:56:3)\n    at processImmediate (internal/timers.js:416:9)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:07.892Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20475,"level":50,"err":{"id":"247ffef0-60c6-11e9-9d7f-e94d0f267b14","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:14.415Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20503,"level":50,"err":{"id":"278bb850-60c6-11e9-a708-772c44f7dd5e","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:19.483Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20531,"level":50,"err":{"id":"2a7da820-60c6-11e9-96db-bfe682f630cd","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)\n    at runNextTicks (internal/process/task_queues.js:56:3)\n    at processImmediate (internal/timers.js:416:9)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:24.436Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20560,"level":50,"err":{"id":"2d5ef620-60c6-11e9-973c-f9aa1d14f812","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:29.254Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20589,"level":50,"err":{"id":"3007cf00-60c6-11e9-ae0b-195b330d4c76","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:33.718Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20617,"level":50,"err":{"id":"327106d0-60c6-11e9-9933-a7915b0600a0","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:37.761Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20645,"level":50,"err":{"id":"35285ea0-60c6-11e9-be7a-871186693404","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:42.319Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20675,"level":50,"err":{"id":"38093770-60c6-11e9-ab59-17e499d8b7fd","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:06:47.151Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20704,"level":50,"err":{"id":"40734cc0-60c6-11e9-bd4a-b7ed90ea006e","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)\n    at runNextTicks (internal/process/task_queues.js:56:3)\n    at processImmediate (internal/timers.js:416:9)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:07:01.292Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20737,"level":50,"err":{"id":"4364c760-60c6-11e9-a096-79307751c2f8","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:07:06.203Z","v":0}
{"name":"Log","hostname":"vultr.guest","pid":20767,"level":50,"err":{"id":"4669ca00-60c6-11e9-8ea4-ad4cf1fc56db","domain":"http://typescript.codes","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"(EADDRINUSE) Cannot start Ghost.","context":"\"Port 2368 is already in use by another program.\"","help":"\"Is another Ghost instance already running?\"","stack":"InternalServerError: (EADDRINUSE) Cannot start Ghost.\n    at new GhostError (/home/www/ghost/core/server/lib/common/errors.js:10:26)\n    at Server.<anonymous> (/home/www/ghost/core/server/ghost-server.js:79:30)\n    at Server.emit (events.js:193:13)\n    at Server.<anonymous> (/usr/local/lib/node-v11.13.0-linux-x64/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:147:37)\n    at emitErrorNT (net.js:1285:8)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)"},"msg":"(EADDRINUSE) Cannot start Ghost.","time":"2019-04-17T04:07:11.270Z","v":0}
